---
ID: "05283740-ebd8-4574-bd21-93bfbfd2f3a0"
Parent: "148cf425-d962-4884-8935-e8733297c2d6"
Template: "148cf425-d962-4884-8935-e8733297c2d6"
Path: /sitecore/templates/Project/OneValtech/Sites/New tenant/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210926T195833Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
